apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-j15y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0025-tenant/tkrw-pr712-0075-0025-app/devfile-sample-j15y@sha256:99ccdfae3efb6af158ffcf25e1f5adfd9a564182491e2a1321ea6815cb653395
        name: my-nodejs
        resources: {}
status: {}
